### ISSUE TITLE
I can't install the package some want to help me

### ISSUE THREAD

**Issue by sento800** [abionics/UltraLight#2]
I can't install the package some want to help me
`Collecting ultralight
  Using cached ultralight-2.1.0.tar.gz (8.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\phuhh\AppData\Local\Temp\pip-install-8yqkga8p\ultralight_e8bd974040714421ab8d1bd6864ada7b\setup.py", line 28, in <module>
          long_description=load_readme(),
                           ^^^^^^^^^^^^^
        File "C:\Users\phuhh\AppData\Local\Temp\pip-install-8yqkga8p\ultralight_e8bd974040714421ab8d1bd6864ada7b\setup.py", line 16, in load_readme
          return read_file('README.md')
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\phuhh\AppData\Local\Temp\pip-install-8yqkga8p\ultralight_e8bd974040714421ab8d1bd6864ada7b\setup.py", line 21, in read_file
          return file.read()
                 ^^^^^^^^^^^
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 60: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by abionics** [comment]
Hi @sento800 , thank you for reporting this! It was an issue with windows encoding. I fixed it, try to install new version using `pip install -U ultralight` or `pip install ultralight==2.2.0`
Please let me know if this fix works for you or if there are any further issues

**Comment by sento800** [comment]
Thank you for helping me
