### ISSUE TITLE
i got this error when run code with cuda

### ISSUE THREAD

**Issue by sento800** [abionics/UltraLight#3]
i got this error when run code with cuda
UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider

**Comment by abionics** [comment]
You should install `onnxruntime-gpu` package instead of `onnxruntime`, see guide in this issue https://github.com/abionics/UltraLight/issues/1

**Comment by sento800** [comment]
i followed but i strangely get this error when i uninstall onnxruntime and install onnxruntime-gpu

Traceback (most recent call last):
  File "d:\workspace\retinaface\utra-light\face_recognition_real_time.py", line 3, in <module>
    from ultralight import UltraLightDetector
  File "D:\workspace\retinaface\utra-light\venv\Lib\site-packages\ultralight\__init__.py", line 7, in <module>
    from ultralight.ultralight import UltraLightDetector
  File "D:\workspace\retinaface\utra-light\venv\Lib\site-packages\ultralight\ultralight.py", line 6, in <module>
    from onnxruntime import InferenceSession
ImportError: cannot import name 'InferenceSession' from 'onnxruntime' (unknown location)

**Comment by abionics** [comment]
Lets try to uninstall both libraries and install it again:

```bash
pip uninstall onnxruntime onnxruntime-gpu -y
pip install onnxruntime-gpu
```

If the exception still exists, check whether the `D:\workspace\retinaface\ultra-light\venv\Lib\site-packages` directory contains the "onnxruntime" folder
